### ISSUE TITLE
In Wiki http://mnode.clube/ cant be reached 

### ISSUE THREAD

**Issue by ValeriiIavtushenko** [rupaya-project/rupaya#1]
In Wiki http://mnode.clube/    cant be reached in masternode monitor
![screen shot 2018-03-22 at 23 44 37](https://user-images.githubusercontent.com/6766737/37800355-3179c8da-2e2b-11e8-83d7-6b82eeb83a37.jpg)

**Comment by pslobo** [comment]
Oops, thanks for catching that. Sometimes I default to Portuguese spelling of the word. Fixed now.
