### ISSUE TITLE
Notice of Copyright Violation

### ISSUE THREAD

**Issue by Iconoclasta** [rupaya-project/rupaya#1]
This is an official notice of Copyright violation against the PIVX developers in which this project has been forked from. The MIT copyright license, and subsequent copyright headers in source files have been modified to explicitly exclude the PIVX developers from all copyrights.

You are hereby notified of an intention to pursue further action if this issue is not acknowledged and formally addressed with a resolution time frame commitment wherein. Failure to acknowledge and correct the violation will result in a formal DMCA take-down notice filed with GitHub Proper after no less than five business days from the date of this notice.

Explicit acknowledgement and referencing progress to maintain compliance MUST be noted in this issue's comments or referred to in any subsequent pull requests to this repository.

**Comment by mo-bay** [comment]
Hey, 

This issue will be fixed A.S.A.P

Is there any particular file you are complaining about?

Regards

**Comment by mo-bay** [comment]
File has been deleted, please let me know if there are any other things, Best Regards

**Comment by Iconoclasta** [comment]
This issue appears to be solved. Thank you for your collaboration. We will stay in contact :).
I'm closing this issue now.
