### ISSUE TITLE
Incorrect data in POS reward breakdown 

### ISSUE THREAD

**Issue by ValeriiIavtushenko** [rupaya-project/rupaya#5]
https://www.rupx.io/reward-breakdown/
in Phase 7 year must be 2019 not 2018

With respect
![screen shot 2018-04-11 at 01 27 28](https://user-images.githubusercontent.com/6766737/38586808-ed8d7836-3d27-11e8-8941-380cf04b0698.jpg)

**Comment by ValeriiIavtushenko** [comment]
And date seems incorrect too

**Comment by rupaya-project** [comment]
fixed!
